services:
  # The MySQL service for the Ghost CMS
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-flexyfile-ghost-dei4hu:/var/lib/mysql
    networks:
      - flexyfile-ghost-dei4hu
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # The Ghost CMS service
  ghost:
    image: ghost:5-alpine
    container_name: ghost_cms_dev
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: "${MYSQL_USER}"
      database__connection__password: "${MYSQL_PASSWORD}"
      database__connection__database: "${MYSQL_DATABASE}"
      database__connection__port: "3306"
      # this url value is just an example, and is likely wrong for your environment!
      url: ${GHOST_HOST}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mysql
    volumes:
      - ghost-flexyfile-ghost-dei4hu:/var/lib/ghost/content
    networks:
      - flexyfile-ghost-dei4hu
    labels:
      - traefik.http.routers.flexyfile-ghost-dei4hu-26-web.rule=Host(`panel.flexyfile.com`)
      - traefik.http.routers.flexyfile-ghost-dei4hu-26-web.entrypoints=web
      - traefik.http.services.flexyfile-ghost-dei4hu-26-web.loadbalancer.server.port=2368
      - traefik.http.routers.flexyfile-ghost-dei4hu-26-web.service=flexyfile-ghost-dei4hu-26-web
      - traefik.enable=true
volumes:
  ghost-flexyfile-ghost-dei4hu: null
  db-flexyfile-ghost-dei4hu: null

networks:
  flexyfile-ghost-dei4hu:
    name: flexyfile-ghost-dei4hu
    external: true
