services:
  # The MySQL service for the Ghost CMS
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=ghostdb
      - MYSQL_USER=ghostuser
      - MYSQL_PASSWORD=example
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # The Ghost CMS service
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: on-failure
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: "ghostuser"
      database__connection__password: "example"
      database__connection__database: "ghostdb"
      database__connection__port: "3306"
      url: http://localhost:2368
    volumes:
      - ghost:/var/lib/ghost/content
    depends_on:
      - mysql
volumes:
  db:
  ghost:
