services:
  # The MySQL service for the Ghost CMS
  mysql:
    image: mysql:8.4.0-oraclelinux8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Tehran
    volumes:
      - db-flexyfile-panel-zbkxy9:/var/lib/mysql
    networks:
      - flexyfile-panel-zbkxy9
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # The Ghost CMS service
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: "${MYSQL_USER}"
      database__connection__password: "${MYSQL_PASSWORD}"
      database__connection__database: "${MYSQL_DATABASE}"
      database__connection__port: "3306"
      url: http://${GHOST_HOST}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ghost-flexyfile-panel-zbkxy9:/var/lib/ghost/content
    networks:
      - flexyfile-panel-zbkxy9
    depends_on:
      - mysql
volumes:
  ghost-flexyfile-panel-zbkxy9: null
  db-flexyfile-panel-zbkxy9: null
networks:
  flexyfile-panel-zbkxy9:
    name: flexyfile-panel-zbkxy9
    external: true
