services:
  # The MySQL service for the Ghost CMS
  mysql:
    image: mysql:8.4.0-oraclelinux8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Jv9!pQ2??xT7@wL6$zR1
      - MYSQL_DATABASE=ghostdb
      - MYSQL_USER=ghostuser
      - MYSQL_PASSWORD=F8s@kL3!vQ9tN??2^bW5&
      - TZ=Asia/Tehran
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # The Ghost CMS service
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql
      database__connection__database: ghostdb
      database__connection__user: ghostuser
      database__connection__password: F8s@kL3!vQ9tN??2^bW5&
      database__connection__port: 3306
      url: http://${GHOST_HOST}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ghost:/var/lib/ghost/content
    depends_on:
      - mysql
volumes:
  db:
  ghost:
